set -g prefix C-a
unbind C-b
bind a send-prefix

bind m setw monitor-activity

unbind *
bind * list-clients

unbind A
bind A command-prompt "rename-window %%"

unbind ^A
bind ^A last-window

unbind ' '
bind ' ' next-window

unbind ^' '
bind ^' ' next-window

unbind ^P
bind ^P previous-window

unbind ^N
bind ^N next-window

unbind K
bind K "kill-window"

unbind x
bind x kill-pane

# Fullscreen
bind F resize-pane -Z
bind S setw synchronize-panes
bind N next-layout
bind P previous-layout
bind J choose-window -F "#{window_index}: #{window_name}" "join-pane -h -t %%"
bind B break-pane
bind k select-pane -U
bind j select-pane -D
bind h select-pane -L
bind l select-pane -R

unbind >
bind > save-buffer /tmp/screen-exchange.txt

unbind ^L
bind ^L refresh-client
unbind l
bind l refresh-client

set -g history-limit 50000

set -g display-time 3000
set -g display-panes-time 2000
setw -g clock-mode-style 24

setw -g mode-keys vi

set -g default-terminal "screen-256color"
# Make highlight in less reverse not italics
# See also: http://superuser.com/questions/891336/fixed-highlighting-in-tmux
set -g terminal-overrides 'xterm*:sitm@,ritm@'

set -g update-environment ''

new -d -s0 -n l0

set -g status-bg white
set -g status-fg blue

set -t0 status-left "#[bg=black,fg=white]#(hostname)#[default]"
set -g status-right "#[fg=red]%H:%M %Y-%m-%d"
set -g status-right-length 50

set -g window-status-current-style fg=red,bright
  
