#!/usr/bin/env bash
# automatic simple sid backport

# check if called binaries are available
for a in dget dpkg-source debuild dpkg apt-mark lynx; do
    hash $a >/dev/null
    if [ ! $? -eq 0 ]; then
        echo $a not found
        exit 1
    fi
done

# check DEBNAME/DEBFULLNAME and set them to robot names if not found
# http://1bm.aiei.ch
export DEBFULLNAME="ARTIFICIAL INTELLIGENCE BACKPORT"
export DEBEMAIL="me@aiei.ch"

# get some storage and do it for the whole archive, prefer leaf packages

# see https://wiki.debian.org/ReduceDebian

# optional version selection
# salsa experimental sid testing stable
# archive.d.o snapshot.d.o

# packages.d.o very unreliable replace it
# wget http://ftp.debian.org/debian/dists/unstable/main/source/Sources.xz
# xzgrep dsc Sources.xz|awk '{print $NF}'|sort -u|wc -l
# http://ftp.debian.org/debian/pool/main/0/0ad/
#dsclink=$(lynx -dump https://packages.debian.org/sid/$1|grep dsc |tail -1|awk '{print $2}')
# operate on source packages
dsclink=$(lynx -dump https://packages.debian.org/source/sid/$1|grep dsc |tail -1|awk '{print $2}')
dscname=$(basename $dsclink)
dscdir=$(echo $dscname | sed s,_.*,,g)

echo $dsclink
echo $dscname
echo $dscdir

# while we rebuild software, can as well
# optimize them for stuff, see optimization
# notes, http://sid.ethz.ch/debian/OPTIMIZE.txt
# binaries and shell scripts: upx and bashx
# image size optimizations, see http://sid.ethz.ch/debian/jpeg/

# time to download
# time to unpack
# time to install build-deps
# time to build
# diskspace src, unpacked, built
# number of files
# sloc

# if root user
#cd /usr/src/
if [ ! -f $dscname ]; then
    dget $dsclink
fi
dpkg-source -x $dscname
cd $dscdir*/
dch --bpo ""
apt build-dep -y .
debuild
cd ..
#apt install ./nvtop*3.0.2*.deb
#apt-mark hold nvtop

# echo $dsclink
# maybe also look at sbuild? ask josch
# if not root, find security hole, get root and GOTO 52.
#thedsc=$(basename $dsclink)
#thename=$(echo $thedsc | sed "s,_.*,,")
# if not root user
#mkdir -p $HOME/src/
#cd $HOME/src/
#dget $dsclink
#dpkg-source -x $thedsc
#cd ${thename}*/
#debuild
