#!/bin/bash

if [ -d debian ]; then
    cd debian
fi

for a in changelog rules control copyright; do
    if [ ! -f $a ]; then
	echo "No debian/$a found"
	exit 1
    fi
done

if [ "${DEBFULLNAME}x" = x ]; then
    echo "WARNING: '\$DEBFULLNAME' not set"
fi
if [ "${DEBEMAIL}x" = x ]; then
    echo "WARNING: '\$DEBEMAIL' not set"
fi

pkg=$(head -1 control|awk '{print $2}')
shortdesc=$(grep ^Description: control|head -1|awk '{$1="";print}')
ver=$(head -1 changelog|awk '{print $2}' |sed 's,(,,g;s,-.*,,g')
auth=$(grep ^Copyright copyright | head -1|awk '{$1="";print}'|grep -v $DEBEMAIL| sed "s,2[0-9][0-9][0-9] ,,g")
url=$(grep ^Homepage: control | head -1|awk '{$1="";print}')
lic=$(grep ^License: copyright | head -1|awk '{$1="";print}')

echo "submit@bugs.debian.org"
echo "ITP: $pkg --$shortdesc"
echo -e 'Package: wnpp\nSeverity: wishlist'
echo "Owner: $DEBFULLNAME <${DEBEMAIL}>"
echo "X-Debbugs-Cc: debian-devel@lists.debian.org"
echo
echo "* Package name    : $pkg"
echo "  Version         : $ver"
echo "  Upstream Authors:$auth"
echo "  URL             :$url"
echo "* License         :$lic"
echo "  Description     :$shortdesc"
sed -n '/Description:.*$/,/^$/p' control |sed 1d | sed -n '/^$/,//!p'
