#!/bin/sh

# Original author: tar@debian.org
# Improved upon by werdahias
# License: GPL-3+
# Used to get a .orig.tar.xz from an upstream without tags/releases.
# Usage: ./git2deb https://some-git-repo.git

set -e

git clone -q --recursive "$1"
name="$(basename "$1" | sed 's/.git$//')"
name_norm=$(echo "$name" | tr '[:upper:]' '[:lower:]')
mv "$name" "$name_norm" && cd "$name_norm" || exit
v="0.0~git$(git log -1 --format=%as | sed  's/-//g').$(git log -1 --format=%h)"
mv "$(pwd)" "$(pwd)-$v"
rm -rf .git && cd ../ || exit
tar -cf "$name_norm-$v".orig.tar "$name_norm-$v"
xz -T0 -q "$name_norm-$v".orig.tar
echo "Successfully created $name_norm-$v.orig.tar.xz"
