#!/bin/bash

if [ "${1}x" = x ]; then
    echo "Syntax: $0 gitrepo [baseversion]"
    #example: $0 git@github.com:NatronGitHub/Natron.git 2.4
    echo
    exit 1
fi

if [ "${2}x" = x ]; then
    ver=0
else
    ver=$2
fi

v=$(date +%Y%m%d)
git clone --recursive $1
n=$(basename $1|sed "s,.git$,,")
nnormalized=$(echo $n| tr '[:upper:]' '[:lower:]')
dir=$(echo ${nnormalized}-${ver}+git${v}+ds)
tar=$(echo ${nnormalized}_${ver}+git${v}+ds.orig.tar)
echo $dir
echo $tar
mv ${n}*/ $dir
rm -rf $dir/.git
# also remove *.dll *.exe *.DLL *.EXE .DS_Store recursively
for a in *.dll *.exe *.DLL *.EXE .DS_Store; do
    find . -name $a -exec rm {} \;
done
tar cf $tar $dir
xz -T0 -v $tar
