#!/bin/bash

# this is not dmidecode

# see https://endoflife.date/raspberry-pi
# or better here https://opensource.com/resources/raspberry-pi
# Raspberry Pi 4 Model B Rev 1.1 2020
# Raspberry Pi 3 Model B Rev 1.2 2016/2018?
# cat /sys/firmware/devicetree/base/model
