#!/bin/sh

# make sure we don't go out of diskspace and too much
# kernels in /boot by removing the older ones (keeps 2)
#
# ensures not the running kernel is removed
#
# myczko@phys.ethz.ch

for a in uname grep tail sed apt-get update-grub wc; do
    which $a >/dev/null
    if [ ! $? -eq 0 ]; then
	echo $a not found
	exit 0
    fi
done

if [ `uname` = Linux ]; then
    if [ ! 0 -eq `id -u` ]; then
	echo "need to be root"
	exit 0
    fi
fi

# could as well be
#ls /boot/vmlinuz-* | grep vmlinuz | sed 's,.*vmlinuz-,,'
n4x=`update-grub 2>&1 | grep vmlinuz | grep "4." | wc -l`
while [ $n4x -gt 2 ]; do
    apt-get --purge remove .*`update-grub 2>&1 | grep "vmlinuz-4." | grep -v $(uname -r) | tail -1 | sed "s,.*vmlinuz-,,"`.* -uy
    n4x=`update-grub 2>&1 | grep vmlinuz | grep "4." | wc -l`
done
