#!/bin/bash

# MIT License
#
# Copyright (c) 2023 Alex Myczko <tar@debian.org>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# run this hourly to update the hw raid test
# either use cron or in a screen `while (./raidhw); do sleep 1h; done`

# try to read server and machine name from config file
if [ -e /etc/sysconfig/xymon-client ]; then . /etc/sysconfig/xymon-client; fi
if [ -e /etc/default/xymon-client ]; then . /etc/default/xymon-client; fi
XYMSRV=$XYMONSERVERS
MACHINE=$CLIENTHOSTNAME

# or set them right in here
#XYMSRV= or set ip directly
#MACHINE=$(hostname -s)

COLUMN=raidhw	  # Name of the column
COLOR=green	    # By default, everything is OK
MSG="HW RAID status"

# only install one of them, if you have multiple different ones, send a patch
which cli64     &>/dev/null && RAIDCHECK="(cli64 curctrl=1 rsf info; cli64 curctrl=1 disk info)"
which perccli64 &>/dev/null && RAIDCHECK="perccli64 /call show|grep -v Time||grep -v ^BBU"
which storcli64 &>/dev/null && RAIDCHECK="storcli64 /call show|grep -v Time"
which arcconf   &>/dev/null && RAIDCHECK="arcconf getconfig 1 pd |grep -v Temperature |grep -v deg\ C|grep -v Sectors| grep -v Service\ Hours|grep -v Estimated\ Life"
which megacli64 &>/dev/null && RAIDCHECK="megacli64 -PDList -aall |grep -v Temperature"

# bail out if no raidtool is found
if [ "x" = "$RAIDCHECK"x ]; then
    echo No RAID found.
    lspci | grep -i raid
    exit 1
fi

# bail out if no reference file is found
if [ ! -e /etc/raidhw.ref ]; then
    echo No RAID reference file found.
    echo Create one using this command:
    echo "$RAIDCHECK" '> /etc/raidhw.ref'
    exit 2
fi


MSG=`diff -u /etc/raidhw.ref <(eval $RAIDCHECK)`
if [ "$?" != 0 ]; then
      COLOR=red
      MSG="${MSG}

      ``
      "
else
      MSG="${MSG}
      $(lspci |grep -i raid)
      All is OK

      $(eval $RAIDCHECK)

      Create a new reference file with:
      $RAIDCHECK > /etc/raidhw.ref
      "
fi

# +70 is lifetime 60 minutes
echo -e "status+70 $MACHINE.$COLUMN $COLOR `date`\n\n${MSG}" | nc -4 -t $XYMSRV 1984

exit 0
