#!/bin/bash
# due to the nature of this software, it will get built into a binary deb package
# then installed, and marked hold
#
# in case later versions of nvtop are needed update them at the src package repo
# used in this installer

dkms status | grep nvidia || (
	echo no nvidia drivers found
	exit 1
)

# check if called binaries are available
for a in dget dpkg-source debuild dpkg apt-mark; do
    hash $a >/dev/null
    if [ ! $? -eq 0 ]; then
        echo $a not found
        exit 1
    fi
done

cd /usr/src/
dget http://deb.debian.org/debian/pool/contrib/n/nvtop/nvtop_3.0.2-1.dsc
dpkg-source -x nvtop_*3.0.2*.dsc
cd nvtop-*3.0.2*/
debuild
cd ..
apt install ./nvtop*3.0.2*.deb
apt-mark hold nvtop
