#!/bin/bash

k=$(uname -r)

# rmadison linux|grep -v debug
# debsnap -l linux|sort -V

# links2 -ssl.certificates 0 -source https://kernel.org/|grep complete|grep tar..z | sed "s,.*ref=.,,g;s,z.*,z,g"
# lynx -dump http://kernel.org/|grep tar..z$|awk '{print $2}'|sort -rVu
