#!/bin/bash

k=$(uname -r)

# rmadison linux|grep -v debug
# debsnap -l linux|sort -V

curl -s https://www.kernel.org/releases.json | jq -r '.releases[] | [.version, .moniker, .source, .released.isodate] | @tsv'
