#!/bin/bash

k=$(uname -r)
export $(echo $k | sed -E 's/^([0-9]+)\.([0-9]+)\.([0-9]+).*/MAJ=\1 MIN=\2 PAT=\3/')

# rmadison linux|grep -v debug
# debsnap -l linux|sort -V

curl -s https://www.kernel.org/releases.json | jq -r '.releases[] | [.version, .moniker, .source, .released.isodate] | @tsv'
