background {
    monitor =
    color = rgba(000000ff)
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M:%S")"
    #text = cmd[update:1000] echo "R'UPTIME\" $(date +"%H%M")"

    font_family = Topaz Unicode KS13
    #font_family = Amalgama
    font_size = 64

    color = rgb(ee8800)
    #color = rgb(eb4b16)

    position = 0, 80
    halign = center
    valign = center
}

input-field {
    monitor =

    size = 220, 60

    position = 0, -80
    halign = center
    valign = center

    font_family = Inter
    font_color = rgb(ffffff)

    outer_color = rgb(ffffff)
    inner_color = rgb(000000)

    check_color = rgb(00ff99)
    fail_color = rgb(ff3333)

    placeholder_text = Password...

    rounding = 8
}
