[window]
opacity = 0.8

[font]
size = 12
offset = { x = -5, y = -5 }

[font.normal]
family = "OCR B S"
#family = "C-64"
#family = "Topaz Unicode KS13"
#family = "Px IBM VGA9"
#family = "OCRA"
#family = "TT2020 Style B"
#family = "Kode Mono Semibold"
#family = "League Mono Narrow Medium"
#family = "Atari"
#style = "Regular"

[colors.primary]
background = "#0044aa"
foreground = "#ffffff"

[cursor]
style = { shape = "Block", blinking = "Always" }
blink_interval = 666
blink_timeout = 0

[cursor.vi_mode_style]
shape = "Block"

[colors.cursor]
cursor = "#ee8800"
text = "#0044aa"
